mybatis-plus:
  configuration:  #mybatis日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server: # 服务端口
  port: 8202
spring:
  cloud:
    nacos: # nacos服务地址
      discovery:
        server-addr: 127.0.0.1:8848
  application:  # 服务名
    name: service-cmn
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root  # mysql数据库连接
    url: jdbc:mysql://localhost:3306/yygh_cmn?characterEncoding=utf-8&useSSL=false
    username: root
  jackson:  #返回json的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:  # 环境设置：dev、test、prod
    active: dev
  redis:
    database: 0
    host: 192.168.6.100
    lettuce:
      pool:
        max-active: 20
        max-idle: 5   #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        min-idle: 0
    port: 6379
    timeout: 1800000

