server: # 服务端口
  port: 8206
spring:
  rabbitmq:
    host: 192.168.6.100
    port: 5672
    username: guest
    password: guest
  application: # 服务名
    name: service-orders
  profiles: # 环境设置：dev、test、prod
    active: dev
  datasource: # mysql数据库连接
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yygh_order?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  jackson: #返回json的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
    mongodb:
      uri: mongodb://192.168.6.100:27017/test
  cloud:
    nacos:
      discovery: # nacos服务地址
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.6.100
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool: #最大阻塞等待时间(负数表示没限制)
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
mybatis-plus:
  configuration: #mybatis日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/yee/yygh/mapper/xml/*.xml
weixin:
  appid: wx74862e0dfcf69954
  partner: 1558950191
  partnerkey: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
  cert: F:\NOTE\apiclient_cert.p12
