server:
  port: 8208
spring:
  application:
    name: service-task
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  profiles:
    active: dev
  rabbitmq:
    host: 192.168.6.100
    password: guest
    port: 5672
    username: guest
  redis:
    database: 0
    host: 192.168.6.100
    lettuce:
      pool:
        max-active: 20
        max-idle: 5
        max-wait: -1
        min-idle: 0
    port: 6379
    timeout: 1800000